spring:
  application:
    name: customer-service
  h2:
    console:
      enabled: true
      path: /h2-console
  
server:
  port: 1001
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
        