spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: E:\WorkSpaces\Spring\GIT
    
server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
        